require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
   - 'config/**/*'
    - 'script/**/*' 
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
Layout/IndentationWidth:
  Width: 2
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case #default
