require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/portfolios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Portfolio. As you add validations to Portfolio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Portfolio.create! valid_attributes
      get portfolios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      portfolio = Portfolio.create! valid_attributes
      get portfolio_url(portfolio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_portfolio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      portfolio = Portfolio.create! valid_attributes
      get edit_portfolio_url(portfolio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Portfolio" do
        expect {
          post portfolios_url, params: { portfolio: valid_attributes }
        }.to change(Portfolio, :count).by(1)
      end

      it "redirects to the created portfolio" do
        post portfolios_url, params: { portfolio: valid_attributes }
        expect(response).to redirect_to(portfolio_url(Portfolio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Portfolio" do
        expect {
          post portfolios_url, params: { portfolio: invalid_attributes }
        }.to change(Portfolio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post portfolios_url, params: { portfolio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested portfolio" do
        portfolio = Portfolio.create! valid_attributes
        patch portfolio_url(portfolio), params: { portfolio: new_attributes }
        portfolio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the portfolio" do
        portfolio = Portfolio.create! valid_attributes
        patch portfolio_url(portfolio), params: { portfolio: new_attributes }
        portfolio.reload
        expect(response).to redirect_to(portfolio_url(portfolio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        portfolio = Portfolio.create! valid_attributes
        patch portfolio_url(portfolio), params: { portfolio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested portfolio" do
      portfolio = Portfolio.create! valid_attributes
      expect {
        delete portfolio_url(portfolio)
      }.to change(Portfolio, :count).by(-1)
    end

    it "redirects to the portfolios list" do
      portfolio = Portfolio.create! valid_attributes
      delete portfolio_url(portfolio)
      expect(response).to redirect_to(portfolios_url)
    end
  end
end
